import Context from './components/Context'
import './globals.scss'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Context>
        <head>
          {/* 카카오 로그인 */}
          <script src="https://developers.kakao.com/sdk/js/kakao.js"></script>
        </head>
        <body>
          <main>{children}</main>
        </body>
      </Context>
    </html>

  )
}
