import Context from './components/Context'
import './globals.scss'

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Context>
        <body>
          <main>{children}</main>
        </body>
      </Context>
    </html>

  )
}
